version: "3.4"

services:
  api-gateway:
    container_name: api-gateway-poc
    depends_on:
      - redis
    build:
      context: .
      dockerfile: prod.Dockerfile
      target: api-gateway
    ports:
      - 3333:3333
  todo:
    container_name: todo-poc
    depends_on:
      - redis
    build:
      context: .
      dockerfile: prod.Dockerfile
      target: todo
  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
